sudo: required

notifications:
  email:
    on_success: always
    on_failure: always

language: cpp

compiler: gcc

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - wget ftp://ftp.unidata.ucar.edu/pub/netcdf/old/netcdf-4.3.1.1.tar.gz
 - wget https://github.com/hfp/libxsmm/archive/master.zip

install:
 - sudo apt-get install -qq g++-4.7 gfortran openmpi-bin openmpi-common libopenmpi-dev hdf5-tools libhdf5-openmpi-dev python-numpy python-scipy python-lxml
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 50 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
 - sudo update-alternatives --set gcc /usr/bin/gcc-4.7
 - tar -xaf netcdf-4.3.1.1.tar.gz
 - cd netcdf-4.3.1.1 && CC=mpicc ./configure --prefix=/usr && make && sudo make install && cd ..
 - unzip master.zip
 - cd libxsmm-master && make generator && sudo cp bin/libxsmm_gemm_generator /usr/bin && cd ..

script:
 - scons compileMode=release order=6 parallelization=hybrid arch=dsnb compiler=gcc unitTests=fast -j2
 - scons compileMode=release order=6 parallelization=hybrid arch=dsnb compiler=gcc unitTests=fast check
 - scons compileMode=release order=6 parallelization=hybrid commThread=yes arch=dsnb compiler=gcc unitTests=fast -j2
 - scons compileMode=release order=6 parallelization=hybrid commThread=yes arch=dsnb compiler=gcc unitTests=fast check
 - scons compileMode=release order=6 parallelization=hybrid netcdf=yes arch=dsnb compiler=gcc unitTests=fast -j2
 - scons compileMode=release order=6 parallelization=hybrid netcdf=yes arch=dsnb compiler=gcc unitTests=fast check
 - scons compileMode=release order=6 parallelization=hybrid hdf5=yes arch=dsnb compiler=gcc unitTests=fast -j2
 - scons compileMode=release order=6 parallelization=hybrid hdf5=yes arch=dsnb compiler=gcc unitTests=fast check
 - scons compileMode=release order=6 parallelization=hybrid netcdf=yes hdf5=yes commThread=yes arch=dsnb compiler=gcc unitTests=fast -j2
 - scons compileMode=release order=6 parallelization=hybrid netcdf=yes hdf5=yes commThread=yes arch=dsnb compiler=gcc unitTests=fast check
 - scons compileMode=release order=6 parallelization=none arch=dsnb compiler=gcc unitTests=fast -j2
 - scons compileMode=release order=6 parallelization=none arch=dsnb compiler=gcc unitTests=fast check
 - scons compileMode=debug order=6 parallelization=hybrid arch=dsnb compiler=gcc unitTests=fast -j2
 - scons compileMode=debug order=6 parallelization=hybrid arch=dsnb compiler=gcc unitTests=fast check
 - scons compileMode=release order=6 parallelization=hybrid arch=ssnb compiler=gcc unitTests=fast -j2
 - scons compileMode=release order=6 parallelization=hybrid arch=ssnb compiler=gcc unitTests=fast check
 - scons compileMode=release order=6 parallelization=hybrid netcdf=yes hdf5=yes commThread=yes arch=ssnb compiler=gcc unitTests=fast -j2
 - scons compileMode=release order=6 parallelization=hybrid netcdf=yes hdf5=yes commThread=yes arch=ssnb compiler=gcc unitTests=fast check
 - scons compileMode=debug order=6 parallelization=hybrid arch=ssnb compiler=gcc unitTests=fast -j2
 - scons compileMode=debug order=6 parallelization=hybrid arch=ssnb compiler=gcc unitTests=fast check
